[package]
name = "binary-util-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4.0"
proc-macro2 = "1.0.56"
quote = "1.0.26"
regex = "1.8.1"
syn = { version = "2.0.13", features = ["full"] }
