[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
private = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.13", features = ["full"] }
